# Generated by Django 4.2 on 2025-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_remove_pendingpetforadoption_adoption_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoptiontable',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petadoptiontable',
            name='id_type',
            field=models.CharField(blank=True, choices=[('e-Card / UMID', 'e-Card / UMID'), ('Employee’s ID / Office ID', 'Employee’s ID / Office ID'), ('Driver’s License', 'Driver’s License'), ('Professional Regulation Commission (PRC) ID', 'Professional Regulation Commission (PRC) ID'), ('Passport', 'Passport'), ('Senior Citizen ID', 'Senior Citizen ID'), ('SSS ID', 'SSS ID'), ('COMELEC / Voter’s ID / COMELEC Registration Form', 'COMELEC / Voter’s ID / COMELEC Registration Form'), ('Philippine Identification (PhilID / ePhilID)', 'Philippine Identification (PhilID / ePhilID)'), ('NBI Clearance', 'NBI Clearance'), ('Integrated Bar of the Philippines (IBP) ID', 'Integrated Bar of the Philippines (IBP) ID'), ('Firearms License', 'Firearms License'), ('AFPSLAI ID', 'AFPSLAI ID'), ('PVAO ID', 'PVAO ID'), ('AFP Beneficiary ID', 'AFP Beneficiary ID'), ('BIR (TIN)', 'BIR (TIN)'), ('Pag-ibig ID', 'Pag-ibig ID'), ('Person’s With Disability (PWD) ID', 'Person’s With Disability (PWD) ID'), ('Solo Parent ID', 'Solo Parent ID'), ('Pantawid Pamilya Pilipino Program (4Ps) ID', 'Pantawid Pamilya Pilipino Program (4Ps) ID'), ('Barangay ID', 'Barangay ID'), ('Philippine Postal ID', 'Philippine Postal ID'), ('Phil-health ID', 'Phil-health ID'), ('School ID', 'School ID'), ('Other valid government-issued IDs or Documents with picture and signature', 'Other valid government-issued IDs or Documents with picture and signature')], max_length=100, null=True),
        ),
    ]
