# Generated by Django 4.2 on 2025-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_petadoptiontable_id_number_petadoptiontable_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpetforadoption',
            name='image_features',
            field=models.BinaryField(null=True),
        ),
    ]
