# Generated by Django 4.2 on 2025-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_pendingpetforadoption_image_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpetforadoption',
            name='image_features',
            field=models.TextField(null=True),
        ),
    ]
