# Generated by Django 4.2 on 2025-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0010_petadoptiontable_id_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpetforadoption',
            name='image_features',
        ),
    ]
